# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DC5255
email: dc5255mx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the web of DC5255 Defcon Group Mexico.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: dc5255mx
github_username:  dc5255

# Build settings
markdown: kramdown
